# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testUItwo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 475)
        self.undoView = QtWidgets.QUndoView(MainWindow)
        self.undoView.setGeometry(QtCore.QRect(30, 10, 631, 441))
        self.undoView.setStyleSheet("QWidget {\n"
"          border: 1px solid black;\n"
"           border-radius: 10px; /* 替换为所需的圆角半径 */\n"
"           background-color: rgb(215, 215, 255); /* 可选：设置背景色 */\n"
"       }")
        self.undoView.setObjectName("undoView")
        self.pushButton = QtWidgets.QPushButton(MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(40, 20, 61, 21))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font: 63 9pt \"Cascadia Code SemiBold\";\n"
"            border-radius: 10px; \n"
"           background-color:rgb(164, 181, 255); \n"
"           color: black; \n"
"       }")
        self.pushButton.setObjectName("pushButton")
        self.undoView_2 = QtWidgets.QUndoView(MainWindow)
        self.undoView_2.setGeometry(QtCore.QRect(60, 70, 131, 331))
        self.undoView_2.setStyleSheet("QWidget {\n"
"           border: 1px solid black;\n"
"           border-radius: 10px; \n"
"           background-color: rgb(199, 219, 255);\n"
"       }\n"
"")
        self.undoView_2.setObjectName("undoView_2")
        self.toolButton_2 = QtWidgets.QToolButton(MainWindow)
        self.toolButton_2.setGeometry(QtCore.QRect(70, 90, 111, 31))
        self.toolButton_2.setStyleSheet("QToolButton {\n"
"    font: 63 9pt \"Cascadia Code SemiBold\";\n"
"            border-radius: 10px; \n"
"           background-color:rgb(164, 181, 255); \n"
"           color: black; \n"
"       }")
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(MainWindow)
        self.toolButton_3.setGeometry(QtCore.QRect(70, 150, 111, 31))
        self.toolButton_3.setStyleSheet("QToolButton {\n"
"    font: 63 9pt \"Cascadia Code SemiBold\";\n"
"            border-radius: 10px; \n"
"           background-color:rgb(164, 181, 255); \n"
"           color: black; \n"
"       }")
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(MainWindow)
        self.toolButton_4.setGeometry(QtCore.QRect(70, 210, 111, 31))
        self.toolButton_4.setStyleSheet("QToolButton {\n"
"    font: 63 9pt \"Cascadia Code SemiBold\";\n"
"            border-radius: 10px; \n"
"           background-color:rgb(164, 181, 255); \n"
"           color: black; \n"
"       }")
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(MainWindow)
        self.toolButton_5.setGeometry(QtCore.QRect(70, 270, 111, 31))
        self.toolButton_5.setStyleSheet("QToolButton {\n"
"    font: 63 9pt \"Cascadia Code SemiBold\";\n"
"            border-radius: 10px; \n"
"           background-color:rgb(164, 181, 255); \n"
"           color: black; \n"
"       }")
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtWidgets.QToolButton(MainWindow)
        self.toolButton_6.setGeometry(QtCore.QRect(70, 330, 111, 31))
        self.toolButton_6.setStyleSheet("QToolButton {\n"
"    font: 63 9pt \"Cascadia Code SemiBold\";\n"
"            border-radius: 10px; \n"
"           background-color:rgb(164, 181, 255); \n"
"           color: black; \n"
"       }")
        self.toolButton_6.setObjectName("toolButton_6")
        self.undoView_3 = QtWidgets.QUndoView(MainWindow)
        self.undoView_3.setGeometry(QtCore.QRect(220, 70, 411, 141))
        self.undoView_3.setStyleSheet("QWidget {\n"
"           border: 1px solid black;\n"
"           border-radius: 10px; \n"
"           background-color: rgb(199, 219, 255);\n"
"       }")
        self.undoView_3.setObjectName("undoView_3")
        self.undoView_4 = QtWidgets.QUndoView(MainWindow)
        self.undoView_4.setGeometry(QtCore.QRect(220, 240, 411, 151))
        self.undoView_4.setStyleSheet("QWidget {\n"
"           border: 1px solid black;\n"
"           border-radius: 10px; \n"
"           background-color: rgb(199, 219, 255);\n"
"       }")
        self.undoView_4.setObjectName("undoView_4")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(360, 90, 121, 16))
        self.label.setStyleSheet("font: 63 9pt \"Cascadia Mono SemiBold\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(380, 260, 71, 16))
        self.label_2.setStyleSheet("font: 63 9pt \"Cascadia Mono SemiBold\";")
        self.label_2.setObjectName("label_2")
        self.toolButton = QtWidgets.QToolButton(MainWindow)
        self.toolButton.setGeometry(QtCore.QRect(240, 320, 121, 51))
        self.toolButton.setStyleSheet("QToolButton {\n"
"    font: 63 9pt \"Cascadia Code SemiBold\";\n"
"            border-radius: 10px; \n"
"           background-color:rgb(164, 181, 255); \n"
"           color: black; \n"
"       }")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_7 = QtWidgets.QToolButton(MainWindow)
        self.toolButton_7.setGeometry(QtCore.QRect(370, 320, 121, 51))
        self.toolButton_7.setStyleSheet("QToolButton {\n"
"    font: 63 9pt \"Cascadia Code SemiBold\";\n"
"            border-radius: 10px; \n"
"           background-color:rgb(164, 181, 255); \n"
"           color: black; \n"
"       }")
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtWidgets.QToolButton(MainWindow)
        self.toolButton_8.setGeometry(QtCore.QRect(500, 320, 121, 51))
        self.toolButton_8.setStyleSheet("QToolButton {\n"
"    font: 63 9pt \"Cascadia Code SemiBold\";\n"
"            border-radius: 10px; \n"
"           background-color:rgb(164, 181, 255); \n"
"           color: black; \n"
"       }")
        self.toolButton_8.setObjectName("toolButton_8")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.pushButton.setText(_translate("MainWindow", "File"))
        self.toolButton_2.setText(_translate("MainWindow", "Modle"))
        self.toolButton_3.setText(_translate("MainWindow", "BachSize"))
        self.toolButton_4.setText(_translate("MainWindow", "Learning Raise"))
        self.toolButton_5.setText(_translate("MainWindow", "Taini info"))
        self.toolButton_6.setText(_translate("MainWindow", "Val info"))
        self.label.setText(_translate("MainWindow", "Training Process"))
        self.label_2.setText(_translate("MainWindow", "precision"))
        self.toolButton.setText(_translate("MainWindow", "Accuracy"))
        self.toolButton_7.setText(_translate("MainWindow", "Loss curve"))
        self.toolButton_8.setText(_translate("MainWindow", "Confusion matrix"))
